name: 'comment-to-issue'
description: 'Provide a description here'
author: 'Your name or organization here'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'heart'
  color: 'red'

# Define your inputs here.
inputs:
  github-token:
    description: 'The GitHub token to use for authentication'
    required: false
    default: ${{ secrets.GITHUB_TOKEN }}
  github-repository:
    description: 'The GitHub repository to use'
    required: false
    default: ${{ github.repository }}
  github-owner:
    description: 'The GitHub owner to use'
    required: false
    default: ${{ github.repository_owner }}
  source-directory:
    description: 'The source directory to use'
    required: false
    default: './'
  file-extension:
    description: 'The file extension to use'
    required: false
    default: '.ts'
  comment-prefixes:
    description: 'The comment prefixes to use'
    required: false
    default: 'TODO,FIXME,BUG,NOTE,OPTIMIZE,IDEA,HACK,REVIEW,DEBUG,QUESTION,WARNING,ERROR,INFO'

# Define your outputs here.
# outputs:
#   time:
#     description: 'Your output description here'

runs:
  using: node20
  main: dist/index.js
